export const taskCopy = {
  fr: {
    tasks: "Tâches du projet",
    schedule: "Planning",
    hint: "Organisez les prochaines étapes du chantier.",
    title: "Nom de la tâche",
    notes: "Notes",
    start: "Date de début",
    due: "Date limite",
    status: "Statut de la tâche",
    todo: "À faire",
    in_progress: "En cours",
    done: "Terminée",
    add: "Nouvelle tâche",
    save: "Enregistrer la tâche",
    edit: "Modifier",
    cancel: "Annuler",
    close: "Fermer",
    remove: "Supprimer",
    confirm: "Supprimer cette tâche ?",
    deleteHint: "Cette suppression est définitive.",
    loading: "Chargement…",
    retry: "Réessayer",
    error: "Impossible de charger les tâches.",
    failed:
      "Enregistrement non confirmé. Vos champs sont conservés. Réessayez ou rechargez pour vérifier.",
    conflict:
      "La tâche a changé ou votre accès a été retiré. Rechargez la version enregistrée avant de réessayer.",
    reload: "Recharger les tâches",
    invalid:
      "Vérifiez le titre et les dates (1900–2100). La date limite doit être égale ou postérieure au début.",
    saved: "Tâche enregistrée.",
    empty: "Aucune tâche à afficher.",
    more: "Charger plus de tâches",
    overdue: "En retard",
    undated: "Sans date",
    week: "Semaine",
    previous: "Semaine précédente",
    next: "Semaine suivante",
    today: "Cette semaine",
    scope:
      "Planning de l’entreprise sélectionnée. Les tâches sur plusieurs jours apparaissent chaque jour.",
    back: "Retour aux projets",
    project: "Projet",
    noDate: "Non définie",
    refresh: "Actualiser",
    loaded: "Tâches chargées",
    deleteFailed: "Suppression non confirmée. Rechargez avant de réessayer.",
    datesHint:
      "Dates facultatives. Une seule date place la tâche sur ce jour ; deux dates définissent une période.",
  },
  en: {
    tasks: "Project tasks",
    schedule: "Schedule",
    hint: "Organize the next steps on site.",
    title: "Task name",
    notes: "Notes",
    start: "Start date",
    due: "Due date",
    status: "Task status",
    todo: "To do",
    in_progress: "In progress",
    done: "Done",
    add: "New task",
    save: "Save task",
    edit: "Edit",
    cancel: "Cancel",
    close: "Close",
    remove: "Delete",
    confirm: "Delete this task?",
    deleteHint: "This deletion is permanent.",
    loading: "Loading…",
    retry: "Try again",
    error: "Could not load tasks.",
    failed:
      "Save not confirmed. Your fields are preserved. Retry or reload to check.",
    conflict:
      "The task changed or your access was removed. Reload the saved version before retrying.",
    reload: "Reload tasks",
    invalid:
      "Check the title and dates (1900–2100). Due date must be on or after the start.",
    saved: "Task saved.",
    empty: "No tasks to display.",
    more: "Load more tasks",
    overdue: "Overdue",
    undated: "Undated",
    week: "Week",
    previous: "Previous week",
    next: "Next week",
    today: "This week",
    scope:
      "Schedule for the selected company. Tasks spanning several days appear on each day.",
    back: "Back to projects",
    project: "Project",
    noDate: "Not set",
    refresh: "Refresh",
    loaded: "Loaded tasks",
    deleteFailed: "Deletion not confirmed. Reload before retrying.",
    datesHint:
      "Dates are optional. One date places the task on that day; two dates define a range.",
  },
};
