export const projectCopy = {
  fr: {
    title: "Projets de l’entreprise",
    hint: "Vos projets sont enregistrés dans cet espace.",
    empty: "Aucun projet pour le moment. Ajoutez votre premier chantier.",
    name: "Nom du projet",
    client: "Client",
    city: "Ville",
    address: "Adresse du chantier (facultatif)",
    create: "Créer le projet",
    cancel: "Annuler",
    loading: "Chargement…",
    retry: "Réessayer",
    error: "Impossible de charger les projets.",
    saveError:
      "Enregistrement non confirmé. Réessayez : le même projet ne sera pas créé deux fois.",
    saved: "Projet enregistré.",
    more: "Voir plus",
    invalid: "Renseignez le projet, le client et la ville.",
  },
  en: {
    title: "Company projects",
    hint: "Your projects are saved in this workspace.",
    empty: "No projects yet. Add your first renovation.",
    name: "Project name",
    client: "Client",
    city: "City",
    address: "Site address (optional)",
    create: "Create project",
    cancel: "Cancel",
    loading: "Loading…",
    retry: "Try again",
    error: "Could not load projects.",
    saveError:
      "Save not confirmed. Try again: the same project will not be created twice.",
    saved: "Project saved.",
    more: "Load more",
    invalid: "Enter the project, client and city.",
  },
};
