export const costCopy = {
  fr: {
    title: "Budget et coûts",
    budget: "Budget de coûts",
    actual: "Coûts réels",
    remaining: "Budget restant",
    over: "Dépassement du budget",
    unset: "Non défini",
    notice:
      "EUR hors taxes. Le budget est une enveloppe de coûts, pas le montant du contrat ni une prévision de marge.",
    materials: "Matériaux",
    labor: "Main-d’œuvre",
    subcontractors: "Sous-traitants",
    other: "Autres",
    editBudget: "Modifier le budget",
    saveBudget: "Enregistrer le budget",
    add: "Ajouter un coût",
    description: "Description du coût",
    amount: "Montant HT (€)",
    date: "Date du coût",
    category: "Catégorie",
    notes: "Notes",
    edit: "Modifier",
    save: "Enregistrer le coût",
    cancel: "Annuler",
    void: "Annuler le coût",
    voided: "Coût annulé",
    confirm: "Annuler ce coût ?",
    voidHint:
      "Le coût sera exclu des totaux mais restera visible dans l’historique. Cette action ne peut pas être annulée.",
    loading: "Chargement…",
    error: "Impossible de charger les coûts.",
    failed:
      "Enregistrement non confirmé. Vos champs sont conservés. Réessayez ou rechargez.",
    conflict:
      "Les données ont changé ou votre accès a été retiré. Rechargez la version enregistrée avant de réessayer.",
    reload: "Recharger les coûts",
    invalid:
      "Vérifiez les champs. Montant positif, deux décimales maximum, jusqu’à 9 999 999,99 € ; dates entre 1900 et 2100.",
    retry: "Réessayer",
    empty: "Aucun coût enregistré.",
    more: "Charger plus",
    close: "Fermer",
    refresh: "Actualiser",
    breakdown: "Répartition des coûts",
    saved: "Enregistré.",
    budgetHint:
      "Saisissez 0 pour un budget nul. Un budget non défini n’est pas un budget nul.",
  },
  en: {
    title: "Budget and costs",
    budget: "Cost budget",
    actual: "Actual costs",
    remaining: "Remaining budget",
    over: "Over budget",
    unset: "Not set",
    notice:
      "EUR excluding tax. The budget is a cost allowance, not the contract value or a margin forecast.",
    materials: "Materials",
    labor: "Labor",
    subcontractors: "Subcontractors",
    other: "Other",
    editBudget: "Edit budget",
    saveBudget: "Save budget",
    add: "Add cost",
    description: "Cost description",
    amount: "Amount excl. tax (€)",
    date: "Cost date",
    category: "Category",
    notes: "Notes",
    edit: "Edit",
    save: "Save cost",
    cancel: "Cancel",
    void: "Void cost",
    voided: "Voided cost",
    confirm: "Void this cost?",
    voidHint:
      "The cost will be excluded from totals but remain visible in the history. This cannot be undone.",
    loading: "Loading…",
    error: "Could not load costs.",
    failed: "Save not confirmed. Your fields are preserved. Retry or reload.",
    conflict:
      "The data changed or your access was removed. Reload the saved version before retrying.",
    reload: "Reload costs",
    invalid:
      "Check the fields. Positive amount, at most two decimals, up to €9,999,999.99; dates between 1900 and 2100.",
    retry: "Try again",
    empty: "No costs recorded.",
    more: "Load more",
    close: "Close",
    refresh: "Refresh",
    breakdown: "Cost breakdown",
    saved: "Saved.",
    budgetHint:
      "Enter 0 for a zero budget. An unset budget is not a zero budget.",
  },
};
