export const teamCopy = {
  fr: {
    close: "Fermer",
    title: "Équipe",
    hint: "Les bonnes personnes, sur les bons chantiers.",
    members: "Membres",
    invitations: "Invitations",
    owner: "Propriétaire",
    member: "Membre",
    email: "E-mail du coéquipier",
    create: "Créer une invitation",
    permission:
      "Les membres consultent les projets, fichiers et tâches, et modifient leurs tâches attribuées. Les finances, le répertoire clients et l’administration sont réservés au propriétaire.",
    transport:
      "Lien valable 7 jours, réservé à cette adresse e-mail vérifiée. Copiez-le pour le partager ; aucun e-mail n’est envoyé automatiquement.",
    link: "Lien d’invitation",
    copy: "Copier le lien",
    copied: "Lien copié",
    pending: "En attente",
    accepted: "Acceptée",
    revoked: "Révoquée",
    expired: "Expirée",
    expires: "Expiration",
    revoke: "Révoquer",
    remove: "Retirer le membre",
    confirm: "Retirer ce membre ?",
    removeHint:
      "Son accès sera retiré, ses invitations révoquées et ses tâches désattribuées. Les projets et fichiers seront conservés.",
    cancel: "Annuler",
    loading: "Chargement…",
    error: "Impossible de charger l’équipe. Réessayez.",
    failed:
      "Action non confirmée. Réessayez ou actualisez pour vérifier le résultat.",
    retry: "Réessayer",
    refresh: "Actualiser",
    more: "Charger plus",
    empty: "Aucune invitation.",
    back: "Retour aux projets",
    ownerOnly: "Accès réservé au propriétaire",
    acceptTitle: "Rejoindre une entreprise",
    accept: "Accepter l’invitation",
    unavailable:
      "Invitation indisponible. Vérifiez que vous utilisez l’adresse e-mail invitée et confirmée. Le lien peut aussi avoir expiré ou été révoqué.",
    signIn: "Se connecter",
    signUp: "Créer un compte",
    signHint:
      "Connectez-vous ou créez un compte avec l’adresse e-mail invitée, puis confirmez cette adresse avant d’accepter.",
    account: "Compte connecté",
    switchAccount: "Changer de compte",
    assignee: "Responsable",
    unassigned: "Non attribuée",
    teamError:
      "Impossible de charger les responsables. Réessayez avant de modifier l’attribution.",
    savedAssignment: "Responsable actuel",
    teamLink: "Gérer l’équipe",
    myTasks: "Mes tâches uniquement",
    readOnly:
      "Consultation uniquement · vous pouvez modifier vos tâches attribuées.",
    denied: "Accès indisponible. Actualisez la page pour réessayer.",
    reset: "Nouvelle invitation",
    resetHint:
      "En cas d’échec, réessayez avec la même adresse ou commencez une nouvelle invitation.",
  },
  en: {
    close: "Close",
    title: "Team",
    hint: "The right people, on the right projects.",
    members: "Members",
    invitations: "Invitations",
    owner: "Owner",
    member: "Member",
    email: "Teammate email",
    create: "Create invitation",
    permission:
      "Members can view projects, files and tasks, and edit their assigned tasks. Finances, the client directory and administration are owner-only.",
    transport:
      "Valid for 7 days and restricted to this verified email address. Copy the link to share it; no email is sent automatically.",
    link: "Invitation link",
    copy: "Copy link",
    copied: "Link copied",
    pending: "Pending",
    accepted: "Accepted",
    revoked: "Revoked",
    expired: "Expired",
    expires: "Expires",
    revoke: "Revoke",
    remove: "Remove member",
    confirm: "Remove this member?",
    removeHint:
      "Their access will be removed, invitations revoked and tasks unassigned. Projects and files will be retained.",
    cancel: "Cancel",
    loading: "Loading…",
    error: "Could not load the team. Try again.",
    failed: "Action not confirmed. Retry or refresh to check the result.",
    retry: "Try again",
    refresh: "Refresh",
    more: "Load more",
    empty: "No invitations.",
    back: "Back to projects",
    ownerOnly: "Owner access required",
    acceptTitle: "Join a company",
    accept: "Accept invitation",
    unavailable:
      "Invitation unavailable. Check that you are using the invited, confirmed email address. The link may also have expired or been revoked.",
    signIn: "Sign in",
    signUp: "Create account",
    signHint:
      "Sign in or create an account with the invited email address, then confirm it before accepting.",
    account: "Signed-in account",
    switchAccount: "Switch account",
    assignee: "Assignee",
    unassigned: "Unassigned",
    teamError:
      "Could not load assignees. Retry before changing the assignment.",
    savedAssignment: "Current assignee",
    teamLink: "Manage team",
    myTasks: "Only my tasks",
    readOnly: "View access · you can edit your assigned tasks.",
    denied: "Access unavailable. Refresh the page to try again.",
    reset: "New invitation",
    resetHint:
      "If a request fails, retry with the same email or start a new invitation.",
  },
};
