export const sketchCopy = {
  fr: {
    title: "Croquis",
    hint: "Dessinez une idée, un plan simple ou une annotation de chantier.",
    new: "Nouveau croquis",
    name: "Nom du croquis",
    create: "Créer le croquis",
    cancel: "Annuler",
    empty: "Aucun croquis enregistré.",
    loading: "Chargement…",
    error: "Impossible de charger les croquis.",
    retry: "Réessayer",
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Enregistré",
    dirty: "Modifications non enregistrées",
    failed:
      "Enregistrement non confirmé. Le dessin reste ouvert ; réessayez pour récupérer la même sauvegarde.",
    conflict:
      "Une autre version a été enregistrée. Exportez votre travail, puis rechargez la version actuelle avant de continuer.",
    invalid:
      "Croquis non pris en charge ou trop volumineux. Maximum 2 000 éléments et 8 Mio, avec images PNG, JPEG ou WebP intégrées.",
    reload: "Recharger la version actuelle",
    download: "Exporter .excalidraw",
    back: "Retour au projet",
    history: "Historique",
    current: "Version actuelle",
    revision: "Version",
    restore: "Utiliser cette version",
    readOnly: "Consultation uniquement",
    autosave:
      "Enregistrement automatique après une pause. Les dimensions indiquées sont des annotations, pas des mesures vérifiées.",
    leave:
      "Des modifications ne sont pas enregistrées. Quitter sans les enregistrer ?",
    open: "Ouvrir",
    more: "Charger plus",
    unsaved: "Pas encore enregistré",
    preview: "Aperçu du croquis",
    refresh: "Actualiser",
    import: "Importer .excalidraw",
    historyHint:
      "Ancienne version · restaurez-la pour enregistrer une nouvelle révision.",
    restoring: "Version restaurée en brouillon : enregistrez pour la publier.",
    missing: "Croquis introuvable ou accès indisponible.",
  },
  en: {
    title: "Sketches",
    hint: "Draw an idea, a simple plan or a site annotation.",
    new: "New sketch",
    name: "Sketch name",
    create: "Create sketch",
    cancel: "Cancel",
    empty: "No sketches saved.",
    loading: "Loading…",
    error: "Could not load sketches.",
    retry: "Try again",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    dirty: "Unsaved changes",
    failed:
      "Save not confirmed. Your drawing is still open; retry to recover the same save.",
    conflict:
      "Another version was saved. Export your work, then reload the current version before continuing.",
    invalid:
      "Unsupported or oversized sketch. Maximum 2,000 elements and 8 MiB, with embedded PNG, JPEG or WebP images.",
    reload: "Reload current version",
    download: "Export .excalidraw",
    back: "Back to project",
    history: "History",
    current: "Current version",
    revision: "Version",
    restore: "Use this version",
    readOnly: "View only",
    autosave:
      "Saves automatically after a pause. Dimension labels are annotations, not verified measurements.",
    leave: "You have unsaved changes. Leave without saving them?",
    open: "Open",
    more: "Load more",
    unsaved: "Not yet saved",
    preview: "Sketch preview",
    refresh: "Refresh",
    import: "Import .excalidraw",
    historyHint: "Older version · restore it to save a new revision.",
    restoring: "Version restored as a draft: save to publish it.",
    missing: "Sketch not found or access unavailable.",
  },
};
