export type LandingLocale = "fr" | "en";
export const landingCopy = {
  fr: {
    title: "RenvoDesk — Logiciel de gestion pour entreprises de rénovation",
    description:
      "Centralisez devis, projets, planning, coûts et documents avec RenvoDesk. Un espace de travail pour les entreprises de rénovation, du bureau au chantier.",
    skip: "Aller au contenu",
    product: "Le produit",
    workflow: "Comment ça marche",
    questions: "Questions",
    login: "Se connecter",
    start: "Créer mon espace",
    demo: "Explorer la démo",
    menu: "Navigation",
    close: "Fermer",
    language: "Read in English",
    eyebrow: "LOGICIEL POUR LES ENTREPRISES DE RÉNOVATION",
    headline: ["Gérez vos chantiers.", "Du devis aux dépenses."],
    intro:
      "RenvoDesk réunit vos devis, tâches, dépenses et documents de chantier. Un logiciel pour les artisans et entreprises de rénovation, au bureau comme sur le terrain.",
    demoNote: "Découvrez le produit avec des données de démonstration.",
    heroTag: "Chaque détail à sa place.",
    heroModel: "Dessin architectural axonométrique avec calques éclatés",
    explode: "Explorer les détails",
    assemble: "Recomposer le projet",
    modelCaption: "Étude de rénovation illustrative · pas un outil de CAO",
    scope: "Pensé pour les entreprises de rénovation",
    regions: "Belgique · France · Pays-Bas",
    devices: "Au bureau comme sur le chantier",
    featureEyebrow: "LES OUTILS POUR PILOTER VOS TRAVAUX",
    featureTitle: "Chiffrez. Organisez.\nSuivez vos dépenses.",
    featureIntro:
      "Fini les devis d’un côté, les photos de l’autre et les dépenses à retrouver. Gardez le contexte de chaque chantier au même endroit.",
    features: [
      {
        title: "Des devis structurés",
        text: "Préparez vos lignes, exportez un PDF et consignez l’envoi ou la décision du client.",
      },
      {
        title: "Des coûts sous les yeux",
        text: "Fixez un budget de coûts et suivez les dépenses de matériaux, de main-d’œuvre et de sous-traitance.",
      },
      {
        title: "Une équipe qui sait où aller",
        text: "Attribuez les tâches, posez les échéances et retrouvez le planning de l’entreprise.",
      },
    ],
    screenshots: {
      caption:
        "Captures de l’application · données fictives · cliquer pour agrandir",
      overview:
        "Vue d’ensemble du chantier : budget de coûts, tâches et journal du projet",
      estimate: "Éditeur de devis avec lignes de travaux, quantités et prix",
      tasks: "Tâches du chantier avec statuts, dates et attribution à l’équipe",
      budget:
        "Budget de coûts et dépenses de matériaux enregistrées pour le chantier",
      labels: ["01 / DEVIS", "02 / ÉQUIPE ET PLANNING", "03 / BUDGET ET COÛTS"],
      titles: [
        "Chiffrez les travaux, ligne par ligne.",
        "Chacun sait ce qu’il doit faire.",
        "Voyez où part le budget du chantier.",
      ],
      descriptions: [
        "Dépose, plomberie, carrelage, pose : détaillez les quantités et les prix. Préparez un devis PDF et consignez la décision du client.",
        "Créez les tâches du chantier, attribuez-les à votre équipe et fixez les échéances. Consultez aussi le planning de l’entreprise.",
        "Enregistrez les achats de matériaux, la main-d’œuvre et la sous-traitance. Retrouvez le budget restant, sans le confondre avec le bénéfice.",
      ],
    },
    preview: {
      caption: "Aperçu du produit · données fictives",
      title: "Maison du Parc",
      location: "Camille Laurent · Bruxelles",
      status: "En cours",
      tabs: ["Vue d’ensemble", "Tâches", "Budget et coûts", "Documents"],
      budget: "Budget de coûts",
      spent: "Dépenses enregistrées",
      remaining: "Budget restant",
      amounts: ["24 000 €", "8 460 €", "15 540 €"],
      tax: "EUR hors taxes · le budget restant n’est pas un bénéfice",
      next: "Prochaines étapes",
      task: "Préparer les murs du séjour",
      task2: "Confirmer la livraison du parquet",
      due: "Cette semaine",
      journal: "Journal du projet",
      event: "Document ajouté",
      filename: "Plan du rez-de-chaussée.pdf",
      time: "Aujourd’hui · 10:42",
      estimate: "Devis de rénovation",
      decision: "Acceptation enregistrée",
    },
    processEyebrow: "DU CONCRET, SUR VOS CHANTIERS",
    processTitle: "Une cuisine à remplacer.\nUn chantier à coordonner.",
    steps: [
      {
        number: "01",
        title: "Avant les travaux : chiffrez une cuisine",
        text: "Regroupez la dépose, les matériaux et la pose dans un devis. Exportez le PDF pour le partager avec votre client.",
      },
      {
        number: "02",
        title: "Pendant les travaux : coordonnez les corps de métier",
        text: "Attribuez les tâches de plomberie, de plâtrerie et de peinture. Retrouvez les échéances et les documents du chantier.",
      },
      {
        number: "03",
        title: "Au fil des achats : contrôlez les dépenses",
        text: "Enregistrez les matériaux, la main-d’œuvre et la sous-traitance. Comparez les dépenses au budget de coûts prévu.",
      },
    ],
    siteEyebrow: "LE CHANTIER NE TIENT PAS DERRIÈRE UN BUREAU",
    siteTitle: "Une photo. Une note.\nEt rien ne se perd.",
    siteText:
      "Sur place, prenez une photo ou enregistrez une note vocale. Au bureau, retrouvez vos documents, vos croquis et l’historique du projet. Le fil reste intact.",
    siteAlt:
      "Intérieur lumineux d’une maison rénovée, cuisine en chêne et pierre naturelle donnant sur un jardin",
    imageCaption: "Illustration architecturale · image générée",
    siteLink: "Voir les projets de démonstration",
    photoLabel: "Photo du chantier",
    attached: "Ajoutée aux documents",
    audioLabel: "Note vocale",
    audioTime: "0:24",
    phoneTitle: "Sur le chantier",
    phoneNote: "Exemple illustratif",
    faqEyebrow: "AVANT DE VOUS LANCER",
    faqTitle: "Quelques réponses,\ntout simplement.",
    faq: [
      {
        q: "À qui s’adresse RenvoDesk ?",
        a: "Aux entreprises de rénovation qui veulent regrouper le suivi de leurs projets : clients, devis, tâches, documents et coûts. L’interface est disponible en français et en anglais.",
      },
      {
        q: "Puis-je découvrir le produit avant de créer un compte ?",
        a: "Oui. La démonstration est accessible sans compte, avec des projets fictifs. Ses modifications ne sont pas enregistrées et les données de démonstration restent séparées de votre espace de travail.",
      },
      {
        q: "Puis-je l’utiliser avec mon équipe ?",
        a: "Oui. Le propriétaire de l’entreprise peut inviter des membres par lien. Les membres accèdent aux projets, aux documents et aux tâches, et modifient les tâches qui leur sont attribuées. Les devis et les coûts restent réservés au propriétaire.",
      },
      {
        q: "RenvoDesk fonctionne-t-il sur téléphone ?",
        a: "Oui, l’interface s’adapte au téléphone pour consulter un projet et ajouter des photos ou des notes vocales. Une connexion internet est nécessaire ; la synchronisation hors ligne n’est pas proposée.",
      },
      {
        q: "Les devis sont-ils envoyés et signés dans RenvoDesk ?",
        a: "Vous pouvez exporter un PDF et enregistrer un envoi, une acceptation ou un refus communiqué ailleurs. L’envoi d’e-mails et la signature électronique ne sont pas encore proposés.",
      },
      {
        q: "La facturation est-elle disponible ?",
        a: "Pas encore. RenvoDesk permet actuellement de préparer les devis et de suivre les budgets de coûts et les dépenses. La facturation, les paiements et la comptabilité ne sont pas intégrés.",
      },
    ],
    ctaEyebrow: "VOTRE PROCHAIN CHANTIER COMMENCE ICI",
    ctaTitle: "Votre prochain chantier.\nUn seul espace pour le gérer.",
    ctaText:
      "Un espace clair pour vos projets, votre équipe et tous les détails qui comptent.",
    footer: "Le logiciel de gestion de vos chantiers.",
    footerNote: "Gestion de projets pour les entreprises de rénovation.",
    top: "Retour en haut",
  },
  en: {
    title: "RenvoDesk — Project management software for renovation companies",
    description:
      "Bring estimates, projects, schedules, costs and documents together with RenvoDesk. One workspace for renovation companies, from the office to the job site.",
    skip: "Skip to content",
    product: "The product",
    workflow: "How it works",
    questions: "Questions",
    login: "Log in",
    start: "Create your workspace",
    demo: "Explore the demo",
    menu: "Navigation",
    close: "Close",
    language: "Lire en français",
    eyebrow: "PROJECT SOFTWARE FOR RENOVATION CONTRACTORS",
    headline: ["Manage your renovations.", "From estimates to costs."],
    intro:
      "RenvoDesk brings your estimates, site tasks, expenses and project documents into one place. Built for renovation contractors, in the office and on site.",
    demoNote: "Get to know the product with fictional demo projects.",
    heroTag: "Every detail in its place.",
    heroModel: "Architectural axonometric drawing with exploded layers",
    explode: "Explore the details",
    assemble: "Bring it together",
    modelCaption: "Illustrative renovation study · not a CAD tool",
    scope: "Made for renovation companies",
    regions: "Belgium · France · The Netherlands",
    devices: "From the office to the job site",
    featureEyebrow: "SEE THE TOOLS YOU WILL WORK WITH",
    featureTitle: "Price the work. Plan the jobs.\nTrack what you spend.",
    featureIntro:
      "Estimates in one place, photos in another, expenses somewhere else. Keep the context of every renovation together.",
    features: [
      {
        title: "Estimates with a clear structure",
        text: "Prepare line items, export a PDF and record sending or the client’s decision.",
      },
      {
        title: "Costs in plain sight",
        text: "Set a cost budget and track materials, labour and subcontractor expenses.",
      },
      {
        title: "A team with a clear next step",
        text: "Assign tasks, set due dates and see the company’s schedule.",
      },
    ],
    screenshots: {
      caption: "Application screenshots · fictional data · click to enlarge",
      overview:
        "Project overview showing the cost budget, site tasks and activity journal",
      estimate:
        "Estimate editor with construction line items, quantities and prices",
      tasks: "Site tasks showing statuses, dates and team assignment controls",
      budget: "Project cost budget and recorded building material expenses",
      labels: [
        "01 / ESTIMATES",
        "02 / TEAM AND SCHEDULE",
        "03 / BUDGET AND COSTS",
      ],
      titles: [
        "Price the work, line by line.",
        "Give every trade a clear next step.",
        "See where the project budget goes.",
      ],
      descriptions: [
        "Demolition, plumbing, tiling, installation: break down quantities and prices. Prepare a PDF estimate and record the client’s decision.",
        "Create site tasks, assign them to your team and set due dates. See the company schedule when you need to plan across projects.",
        "Record materials, labour and subcontractor expenses. See what remains of your cost budget, without confusing it with profit.",
      ],
    },
    preview: {
      caption: "Product preview · fictional data",
      title: "Maison du Parc",
      location: "Camille Laurent · Brussels",
      status: "In progress",
      tabs: ["Overview", "Tasks", "Budget & costs", "Documents"],
      budget: "Cost budget",
      spent: "Recorded expenses",
      remaining: "Budget remaining",
      amounts: ["€24,000", "€8,460", "€15,540"],
      tax: "EUR excluding tax · remaining budget is not profit",
      next: "Next steps",
      task: "Prepare the living room walls",
      task2: "Confirm the flooring delivery",
      due: "This week",
      journal: "Project journal",
      event: "Document added",
      filename: "Ground-floor-plan.pdf",
      time: "Today · 10:42",
      estimate: "Renovation estimate",
      decision: "Acceptance recorded",
    },
    processEyebrow: "BUILT AROUND REAL RENOVATION WORK",
    processTitle: "A kitchen to replace.\nA renovation to coordinate.",
    steps: [
      {
        number: "01",
        title: "Before work: price a kitchen renovation",
        text: "Put demolition, materials and installation into an itemised estimate. Export the PDF to share with your client.",
      },
      {
        number: "02",
        title: "During work: coordinate the trades",
        text: "Assign plumbing, plastering and painting tasks. Keep due dates and site documents together for your team.",
      },
      {
        number: "03",
        title: "As you buy: keep track of project spending",
        text: "Record materials, labour and subcontractor expenses. Compare recorded spending with the cost budget you set.",
      },
    ],
    siteEyebrow: "GOOD WORK DOESN’T STAY BEHIND A DESK",
    siteTitle: "A photo. A note.\nNothing lost along the way.",
    siteText:
      "On site, capture a photo or record a voice note. Back at your desk, find the documents, sketches and project history. Pick up right where you left off.",
    siteAlt:
      "Light-filled renovated townhouse with an oak and natural stone kitchen opening onto a garden",
    imageCaption: "Architectural illustration · generated image",
    siteLink: "Explore the demo projects",
    photoLabel: "Site photo",
    attached: "Added to documents",
    audioLabel: "Voice note",
    audioTime: "0:24",
    phoneTitle: "On the job site",
    phoneNote: "Illustrative example",
    faqEyebrow: "BEFORE YOU GET STARTED",
    faqTitle: "A few answers.\nPlain and simple.",
    faq: [
      {
        q: "Who is RenvoDesk for?",
        a: "Renovation companies that want to bring project work together: clients, estimates, tasks, documents and costs. The interface is available in French and English.",
      },
      {
        q: "Can I explore before creating an account?",
        a: "Yes. The demo is available without an account and uses fictional projects. Changes reset on reload, and demo records remain separate from your saved workspace.",
      },
      {
        q: "Can I use it with my team?",
        a: "Yes. Company owners can invite members using a link. Members access projects, documents and tasks, and edit the tasks assigned to them. Estimates and costs remain owner-only.",
      },
      {
        q: "Does RenvoDesk work on a phone?",
        a: "Yes. The interface adapts to your phone for viewing projects and capturing photos or voice notes. An internet connection is required; offline synchronisation is not available.",
      },
      {
        q: "Are estimates emailed and signed in RenvoDesk?",
        a: "You can export a PDF and record sending, acceptance or decline communicated elsewhere. Email delivery and electronic signatures are not available yet.",
      },
      {
        q: "Is invoicing available?",
        a: "Not yet. RenvoDesk currently supports estimate preparation, cost budgets and expense tracking. Invoicing, payments and accounting are not integrated.",
      },
    ],
    ctaEyebrow: "YOUR NEXT PROJECT STARTS HERE",
    ctaTitle: "Your next renovation.\nOne place to manage it.",
    ctaText:
      "A clear workspace for your projects, your team and the details that matter.",
    footer: "Project software for renovation contractors.",
    footerNote: "Project management for renovation companies.",
    top: "Back to top",
  },
} as const;
