export const fileCopy = {
  fr: {
    title: "Fichiers du projet",
    hint: "PDF, JPG, PNG, WebP, TXT, DOCX, XLSX · 10 Mio maximum par fichier.",
    choose: "Choisir un fichier",
    drag: "Glissez un fichier ici, ou choisissez-le ci-dessous.",
    drop: "Déposez le fichier ici.",
    single: "Importez un seul fichier à la fois.",
    upload: "Importer",
    retry: "Réessayer",
    loading: "Chargement…",
    empty: "Aucun fichier pour ce projet.",
    invalid:
      "Choisissez un fichier pris en charge, non vide, de 10 Mio maximum.",
    heic: "HEIC/HEIF n’est pas encore pris en charge. Convertissez la photo en JPG ou PNG.",
    error:
      "L’opération n’a pas abouti. Réessayez ; un transfert incomplet peut être vérifié ou supprimé.",
    loadError: "Impossible de charger les fichiers.",
    pending: "Import incomplet",
    deleting: "Suppression à terminer",
    verify: "Vérifier l’import",
    download: "Télécharger",
    preview: "Aperçu",
    remove: "Supprimer",
    cancel: "Annuler",
    deleteTitle: "Supprimer ce fichier ?",
    deleteHint:
      "Le fichier sera supprimé du stockage du projet. Cette action est irréversible.",
    close: "Fermer",
    previewHint:
      "Aperçu privé temporaire. Téléchargez le fichier si votre navigateur ne peut pas l’afficher.",
    more: "Voir plus",
    success: "Import terminé.",
    deleted: "Fichier supprimé.",
    expired: "L’aperçu a expiré. Fermez-le puis ouvrez-le à nouveau.",
    progress: "Progression de l’import",
  },
  en: {
    title: "Project files",
    hint: "PDF, JPG, PNG, WebP, TXT, DOCX, XLSX · up to 10 MiB per file.",
    choose: "Choose a file",
    drag: "Drag a file here, or choose one below.",
    drop: "Drop your file here.",
    single: "Upload one file at a time.",
    upload: "Upload",
    retry: "Try again",
    loading: "Loading…",
    empty: "No files for this project yet.",
    invalid: "Choose a supported, non-empty file up to 10 MiB.",
    heic: "HEIC/HEIF is not supported yet. Convert the photo to JPG or PNG.",
    error:
      "The operation did not finish. Retry; incomplete uploads can be verified or removed.",
    loadError: "Could not load files.",
    pending: "Incomplete upload",
    deleting: "Deletion needs completing",
    verify: "Verify upload",
    download: "Download",
    preview: "Preview",
    remove: "Delete",
    cancel: "Cancel",
    deleteTitle: "Delete this file?",
    deleteHint:
      "The file will be removed from project storage. This cannot be undone.",
    close: "Close",
    previewHint:
      "Temporary private preview. Download the file if your browser cannot display it.",
    more: "Load more",
    success: "Upload complete.",
    deleted: "File deleted.",
    expired: "Preview expired. Close it and open it again.",
    progress: "Upload progress",
  },
};
