export const activityCopy = {
  fr: {
    title: "Journal du projet",
    description: "Les changements enregistrés, au fil du chantier.",
    all: "Toute l’activité",
    project: "Projet",
    tasks: "Tâches",
    documents: "Documents",
    estimates: "Devis",
    costs: "Coûts",
    filter: "Type d’activité",
    refresh: "Actualiser",
    older: "Charger les activités précédentes",
    loading: "Chargement du journal…",
    error: "Impossible de charger le journal.",
    retry: "Réessayer",
    empty: "Aucune activité enregistrée pour le moment.",
    emptyFilter: "Aucune activité de ce type.",
    since: "Activité enregistrée depuis le",
    you: "Vous",
    member: "Membre de l’équipe",
    system: "Système",
    unknown: "Activité du projet",
    open: "Ouvrir",
    tax: "hors taxes",
    revision: "Révision",
    changed: "Modifications",
    events: {
      "project.created": "Projet créé",
      "project.updated": "Projet modifié",
      "task.created": "Tâche créée",
      "task.updated": "Tâche modifiée",
      "task.deleted": "Tâche supprimée",
      "estimate.created": "Brouillon de devis créé",
      "estimate.updated": "Brouillon de devis modifié",
      "estimate.sent": "Envoi du devis enregistré",
      "estimate.accepted": "Acceptation du devis enregistrée",
      "estimate.declined": "Refus du devis enregistré",
      "budget.created": "Budget de coûts défini",
      "budget.updated": "Budget de coûts modifié",
      "cost.created": "Dépense ajoutée",
      "cost.updated": "Dépense corrigée",
      "cost.voided": "Dépense annulée",
      "file.added": "Document ajouté",
      "file.deleted": "Document supprimé",
      "sketch.created": "Croquis créé",
      "sketch.published": "Révision du croquis enregistrée",
    },
    statuses: {
      planning: "En préparation",
      active: "En cours",
      completed: "Terminé",
      todo: "À faire",
      in_progress: "En cours",
      done: "Terminée",
    },
    fields: {
      name: "nom",
      client_name: "client",
      city: "ville",
      address: "adresse",
      status: "statut",
      client_id: "client lié",
      property_id: "bien lié",
      title: "titre",
      notes: "notes",
      start_date: "date de début",
      due_date: "échéance",
      assignee_id: "responsable",
      lines: "lignes",
      budget_cents: "budget",
      description: "description",
      category: "catégorie",
      amount_cents: "montant",
      incurred_on: "date",
      voided: "annulation",
    },
  },
  en: {
    title: "Project journal",
    description: "Saved changes, as the project progresses.",
    all: "All activity",
    project: "Project",
    tasks: "Tasks",
    documents: "Documents",
    estimates: "Estimates",
    costs: "Costs",
    filter: "Activity type",
    refresh: "Refresh",
    older: "Load older activity",
    loading: "Loading journal…",
    error: "Could not load the journal.",
    retry: "Try again",
    empty: "No activity recorded yet.",
    emptyFilter: "No activity of this type.",
    since: "Activity recorded since",
    you: "You",
    member: "Team member",
    system: "System",
    unknown: "Project activity",
    open: "Open",
    tax: "excluding tax",
    revision: "Revision",
    changed: "Changed",
    events: {
      "project.created": "Project created",
      "project.updated": "Project updated",
      "task.created": "Task created",
      "task.updated": "Task updated",
      "task.deleted": "Task deleted",
      "estimate.created": "Estimate draft created",
      "estimate.updated": "Estimate draft updated",
      "estimate.sent": "Estimate sending recorded",
      "estimate.accepted": "Estimate acceptance recorded",
      "estimate.declined": "Estimate decline recorded",
      "budget.created": "Cost budget set",
      "budget.updated": "Cost budget updated",
      "cost.created": "Expense added",
      "cost.updated": "Expense corrected",
      "cost.voided": "Expense voided",
      "file.added": "Document added",
      "file.deleted": "Document deleted",
      "sketch.created": "Sketch created",
      "sketch.published": "Sketch revision saved",
    },
    statuses: {
      planning: "Planning",
      active: "Active",
      completed: "Completed",
      todo: "To do",
      in_progress: "In progress",
      done: "Done",
    },
    fields: {
      name: "name",
      client_name: "client",
      city: "city",
      address: "address",
      status: "status",
      client_id: "linked client",
      property_id: "linked property",
      title: "title",
      notes: "notes",
      start_date: "start date",
      due_date: "due date",
      assignee_id: "assignee",
      lines: "lines",
      budget_cents: "budget",
      description: "description",
      category: "category",
      amount_cents: "amount",
      incurred_on: "date",
      voided: "void status",
    },
  },
};
