export const clientCopy = {
  fr: {
    title: "Clients et biens",
    hint: "Contacts réutilisables et adresses de chantier.",
    name: "Nom du client",
    kind: "Type de client",
    individual: "Particulier",
    company: "Entreprise",
    email: "E-mail du client",
    phone: "Téléphone du client",
    billing_address: "Adresse de facturation",
    add: "Ajouter un client",
    edit: "Modifier",
    save: "Enregistrer le client",
    cancel: "Annuler",
    search: "Rechercher un client",
    submit: "Rechercher",
    loading: "Chargement…",
    error: "Impossible de charger les clients ou les biens.",
    retry: "Réessayer",
    failed:
      "Enregistrement non confirmé. Vos champs sont conservés ; réessayez.",
    conflict:
      "Les données ont changé ou votre accès a été retiré. Rechargez avant de modifier à nouveau.",
    reload: "Recharger et remplacer mes champs",
    empty: "Aucun client trouvé.",
    more: "Charger plus",
    properties: "Biens du client",
    addProperty: "Ajouter un bien",
    saveProperty: "Enregistrer le bien",
    label: "Nom du bien",
    address: "Adresse du bien",
    city: "Ville du bien",
    country: "Pays du bien",
    noProperties: "Aucun bien enregistré.",
    none: "Saisie manuelle",
    choose: "Client enregistré (facultatif)",
    chooseProperty: "Bien enregistré (facultatif)",
    snapshot:
      "Les coordonnées choisies sont copiées dans ce projet. Les modifications du répertoire ne mettront pas à jour les projets existants.",
    select: "Ouvrir le client",
    back: "Retour aux projets",
  },
  en: {
    title: "Clients and properties",
    hint: "Reusable contacts and site addresses.",
    name: "Client name",
    kind: "Client type",
    individual: "Individual",
    company: "Company",
    email: "Client email",
    phone: "Client phone",
    billing_address: "Billing address",
    add: "Add client",
    edit: "Edit",
    save: "Save client",
    cancel: "Cancel",
    search: "Search clients",
    submit: "Search",
    loading: "Loading…",
    error: "Could not load clients or properties.",
    retry: "Try again",
    failed: "Save not confirmed. Your fields are preserved; retry.",
    conflict:
      "The data changed or your access was removed. Reload before editing again.",
    reload: "Reload and replace my fields",
    empty: "No clients found.",
    more: "Load more",
    properties: "Client properties",
    addProperty: "Add property",
    saveProperty: "Save property",
    label: "Property name",
    address: "Property address",
    city: "Property city",
    country: "Property country",
    noProperties: "No properties saved.",
    none: "Enter manually",
    choose: "Saved client (optional)",
    chooseProperty: "Saved property (optional)",
    snapshot:
      "Selected details are copied into this project. Directory edits will not update existing projects.",
    select: "Open client",
    back: "Back to projects",
  },
};
